GAME_SIZE = 3
TILE_SIZE = 175

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 600
FIELD_SIZE = FIELD_W, FIELD_H = GAME_SIZE + 3, GAME_SIZE + 3
FIELD_RES = FIELD_W * TILE_SIZE, FIELD_H * TILE_SIZE

FPS = 60
BLANK = None

BACKGROUND_COLOR = (25, 25, 25)

BASIC_FONT_SIZE = 25
BUTTON_FONT_SIZE = 40
NUMBER_TILES_FONT_SIZE = 60

UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'